# Generated by Django 6.0.5 on 2026-05-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='level',
        ),
    ]
